## NumPy Exercise
### Task: Create NumPy code that accomplishes the following simple task
#### 1) Create a NumPy array that starts in 0 and finishes at 10 and contains the even numbers between 0 and 10

In [2]:
import numpy as np
import pandas as pd

# Even numbers between 0 and 10
even = np.arange(0, 10)
even = even[even%2 == 0]
print(even)

[0 2 4 6 8]


#### 2) Create a NumPy array with matrix [2, 1; 6, 3]

In [7]:
# Create matrix [2 1;6 3]
matrix = np.array([[2, 1], [6, 3]])
print(matrix)

[[2 1]
 [6 3]]


#### 3) Multiply the matrix you created with identity matrix [1 0; 0 1]

In [10]:
# Create identity matrix [1 0; 0 1]
eye = np.identity(2)
print(eye)

# Multiply the matrix with identity
multiply = np.dot(matrix, eye)
print(multiply)

[[1. 0.]
 [0. 1.]]
[[2. 1.]
 [6. 3.]]


#### 4) Sum the columns of the matrix created in part 2

In [13]:
# Sum the column of the matrix
col_sum = np.sum(matrix, axis=0)
print(col_sum)

[8 4]
